name: JS Checks

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  js-checks:
    uses: hemilabs/.github/.github/workflows/js-checks.yml@2900f1ef5a775d5d1f96ae012f5ad5d6e98cd6ec # v1.3.1
