name: JS Checks

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  js-checks:
    uses: hemilabs/actions/.github/workflows/js-checks.yml@c86350368ebf1124e81813d1497fb44606f3b6c1 # v2.0.0
